Console.Clear();
Console.WriteLine("... Contagem de 0 à 10 ...");
         Console.WriteLine(); 
    Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine("precione uma tecla para começar");
Console.ResetColor();
Console.ReadKey();
                             Console.Clear();
         Console.WriteLine(); 
                        Thread.Sleep(1000);
                                   
Console.Write(0);          Console.Beep(1349, 100);
                        Thread.Sleep(1000);
Console.Write(",1");          Console.Beep(1349, 100);
                        Thread.Sleep(1000);
Console.Write(",2");          Console.Beep(1349, 100);
                        Thread.Sleep(1000);
Console.Write(",3");          Console.Beep(1349, 100);
                        Thread.Sleep(1000);
Console.Write(",4");          Console.Beep(1349, 100);
                        Thread.Sleep(1000);
Console.Write(",5");          Console.Beep(1349, 100);
                        Thread.Sleep(1000);
Console.Write(",6");          Console.Beep(1349, 100);
                        Thread.Sleep(1000);
Console.Write(",7");          Console.Beep(1349, 100);
                        Thread.Sleep(1000);
Console.Write(",8");          Console.Beep(1349, 100);
                        Thread.Sleep(1000);
Console.Write(",9");          Console.Beep(1349, 100);
                        Thread.Sleep(1000);
Console.Write(",10");          Console.Beep(2050, 500);
Console.WriteLine();
       Console.ForegroundColor = ConsoleColor.Red;
Console.WriteLine("finalizado");
                       Console.ResetColor();
